server:
  port: 40406
  forward-headers-strategy: native
  error:
    include-message: always
spring:
  devtools:
    restart:
      eanbled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
      resolve-lazily: true
  data:
    redis:
      repositories:
        enabled: false
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: [ 'httptrace', 'metrics', 'env', 'logfile', 'health' ]
  health:
    redis:
      enabled: false
logging:
  level:
    run.yuque.app: INFO
    org.eclipse.jetty.server.HttpChannel: ERROR
  file:
    path: ${yuque.work-dir}/logs

springfox:
  documentation:
    enabled: false

yuque:
  download-timeout: 5m
  cache: memory
  work-dir: ${user.home}/.yuque
  halo:
    username: ridup
    password: 123456
    host: https://ridup.cn
